package com.expense.management.ui.theme

import androidx.compose.ui.graphics.Color

// Financial Globals
val IncomeGreen = Color(0xFF43A047)
val ExpenseRed = Color(0xFFE53935)

// ------------------------------------------------------------------
// Material You (fallback brand palette)
// ------------------------------------------------------------------
val MyPrimaryLight = Color(0xFF3F51B5)
val MyOnPrimaryLight = Color(0xFFFFFFFF)
val MyPrimaryContainerLight = Color(0xFFE8EAF6)
val MyOnPrimaryContainerLight = Color(0xFF1A237E)
val MySecondaryLight = Color(0xFF009688)
val MyOnSecondaryLight = Color(0xFFFFFFFF)
val MySecondaryContainerLight = Color(0xFFE0F2F1)
val MyOnSecondaryContainerLight = Color(0xFF004D40)
val MyTertiaryLight = Color(0xFFFF9800)
val MyOnTertiaryLight = Color(0xFFFFFFFF)
val MyBackgroundLight = Color(0xFFF5F5F5)
val MyOnBackgroundLight = Color(0xFF1C1B1F)
val MySurfaceLight = Color(0xFFFFFFFF)
val MyOnSurfaceLight = Color(0xFF1C1B1F)
val MySurfaceVariantLight = Color(0xFFE7E0EC)
val MyOnSurfaceVariantLight = Color(0xFF49454F)
val MyOutlineLight = Color(0xFF79747E)
val MyErrorLight = Color(0xFFE53935)
val MyOnErrorLight = Color(0xFFFFFFFF)

val MyPrimaryDark = Color(0xFF9FA8DA)
val MyOnPrimaryDark = Color(0xFF001054)
val MyPrimaryContainerDark = Color(0xFF1A237E)
val MyOnPrimaryContainerDark = Color(0xFFE8EAF6)
val MySecondaryDark = Color(0xFF80CBC4)
val MyOnSecondaryDark = Color(0xFF003631)
val MySecondaryContainerDark = Color(0xFF004D40)
val MyOnSecondaryContainerDark = Color(0xFFE0F2F1)
val MyTertiaryDark = Color(0xFFFFCC80)
val MyOnTertiaryDark = Color(0xFF4E2C00)
val MyBackgroundDark = Color(0xFF121212)
val MyOnBackgroundDark = Color(0xFFE0E0E0)
val MySurfaceDark = Color(0xFF1E1E1E)
val MyOnSurfaceDark = Color(0xFFE0E0E0)
val MySurfaceVariantDark = Color(0xFF49454F)
val MyOnSurfaceVariantDark = Color(0xFFCAC4D0)
val MyOutlineDark = Color(0xFF938F99)
val MyErrorDark = Color(0xFFCF6679)
val MyOnErrorDark = Color(0xFF37000B)

// ------------------------------------------------------------------
// Nordic
// ------------------------------------------------------------------
val NordicPrimaryLight = Color(0xFF5E81AC)
val NordicOnPrimaryLight = Color(0xFFFFFFFF)
val NordicPrimaryContainerLight = Color(0xFFD8DEE9)
val NordicOnPrimaryContainerLight = Color(0xFF2E3440)
val NordicSecondaryLight = Color(0xFF88C0D0)
val NordicOnSecondaryLight = Color(0xFF2E3440)
val NordicSecondaryContainerLight = Color(0xFFE5E9F0)
val NordicOnSecondaryContainerLight = Color(0xFF3B4252)
val NordicTertiaryLight = Color(0xFFB48EAD)
val NordicOnTertiaryLight = Color(0xFFFFFFFF)
val NordicBackgroundLight = Color(0xFFECEFF4)
val NordicOnBackgroundLight = Color(0xFF2E3440)
val NordicSurfaceLight = Color(0xFFFFFFFF)
val NordicOnSurfaceLight = Color(0xFF2E3440)
val NordicSurfaceVariantLight = Color(0xFFE5E9F0)
val NordicOnSurfaceVariantLight = Color(0xFF4C566A)
val NordicOutlineLight = Color(0xFF4C566A)
val NordicErrorLight = Color(0xFFBF616A)
val NordicOnErrorLight = Color(0xFFFFFFFF)

val NordicPrimaryDark = Color(0xFF81A1C1)
val NordicOnPrimaryDark = Color(0xFF2E3440)
val NordicPrimaryContainerDark = Color(0xFF4C566A)
val NordicOnPrimaryContainerDark = Color(0xFFD8DEE9)
val NordicSecondaryDark = Color(0xFF8FBCBB)
val NordicOnSecondaryDark = Color(0xFF2E3440)
val NordicSecondaryContainerDark = Color(0xFF434C5E)
val NordicOnSecondaryContainerDark = Color(0xFFD8DEE9)
val NordicTertiaryDark = Color(0xFFB48EAD)
val NordicOnTertiaryDark = Color(0xFF2E3440)
val NordicBackgroundDark = Color(0xFF2E3440)
val NordicOnBackgroundDark = Color(0xFFECEFF4)
val NordicSurfaceDark = Color(0xFF3B4252)
val NordicOnSurfaceDark = Color(0xFFECEFF4)
val NordicSurfaceVariantDark = Color(0xFF434C5E)
val NordicOnSurfaceVariantDark = Color(0xFFD8DEE9)
val NordicOutlineDark = Color(0xFF4C566A)
val NordicErrorDark = Color(0xFFBF616A)
val NordicOnErrorDark = Color(0xFF2E3440)

// ------------------------------------------------------------------
// Cyberpunk
// ------------------------------------------------------------------
val CyberPrimaryLight = Color(0xFF00BFA5)
val CyberOnPrimaryLight = Color(0xFF000000)
val CyberPrimaryContainerLight = Color(0xFFE0F7FA)
val CyberOnPrimaryContainerLight = Color(0xFF004D40)
val CyberSecondaryLight = Color(0xFFD500F9)
val CyberOnSecondaryLight = Color(0xFFFFFFFF)
val CyberSecondaryContainerLight = Color(0xFFF3E5F5)
val CyberOnSecondaryContainerLight = Color(0xFF4A148C)
val CyberTertiaryLight = Color(0xFF0091EA)
val CyberOnTertiaryLight = Color(0xFFFFFFFF)
val CyberBackgroundLight = Color(0xFFF5F5F5)
val CyberOnBackgroundLight = Color(0xFF212121)
val CyberSurfaceLight = Color(0xFFFFFFFF)
val CyberOnSurfaceLight = Color(0xFF212121)
val CyberSurfaceVariantLight = Color(0xFFEEEEEE)
val CyberOnSurfaceVariantLight = Color(0xFF616161)
val CyberOutlineLight = Color(0xFF9E9E9E)
val CyberErrorLight = Color(0xFFFF1744)
val CyberOnErrorLight = Color(0xFFFFFFFF)

val CyberPrimaryDark = Color(0xFF39FF14)
val CyberOnPrimaryDark = Color(0xFF000000)
val CyberPrimaryContainerDark = Color(0xFF1A331A)
val CyberOnPrimaryContainerDark = Color(0xFF39FF14)
val CyberSecondaryDark = Color(0xFFFF10F0)
val CyberOnSecondaryDark = Color(0xFF000000)
val CyberSecondaryContainerDark = Color(0xFF330033)
val CyberOnSecondaryContainerDark = Color(0xFFFF10F0)
val CyberTertiaryDark = Color(0xFF00F0FF)
val CyberOnTertiaryDark = Color(0xFF000000)
val CyberBackgroundDark = Color(0xFF000000)
val CyberOnBackgroundDark = Color(0xFFE0E0E0)
val CyberSurfaceDark = Color(0xFF0D0D0D)
val CyberOnSurfaceDark = Color(0xFFE0E0E0)
val CyberSurfaceVariantDark = Color(0xFF1A1A1A)
val CyberOnSurfaceVariantDark = Color(0xFFBDBDBD)
val CyberOutlineDark = Color(0xFF424242)
val CyberErrorDark = Color(0xFFFF1744)
val CyberOnErrorDark = Color(0xFF000000)

// ------------------------------------------------------------------
// Corporate
// ------------------------------------------------------------------
val CorpPrimaryLight = Color(0xFF1E3A8A)
val CorpOnPrimaryLight = Color(0xFFFFFFFF)
val CorpPrimaryContainerLight = Color(0xFFDBEAFE)
val CorpOnPrimaryContainerLight = Color(0xFF1E3A8A)
val CorpSecondaryLight = Color(0xFF0F4C81)
val CorpOnSecondaryLight = Color(0xFFFFFFFF)
val CorpSecondaryContainerLight = Color(0xFFE0F2FE)
val CorpOnSecondaryContainerLight = Color(0xFF0F4C81)
val CorpTertiaryLight = Color(0xFFD97706)
val CorpOnTertiaryLight = Color(0xFFFFFFFF)
val CorpBackgroundLight = Color(0xFFF9FAFB)
val CorpOnBackgroundLight = Color(0xFF111827)
val CorpSurfaceLight = Color(0xFFFFFFFF)
val CorpOnSurfaceLight = Color(0xFF111827)
val CorpSurfaceVariantLight = Color(0xFFF3F4F6)
val CorpOnSurfaceVariantLight = Color(0xFF6B7280)
val CorpOutlineLight = Color(0xFF9CA3AF)
val CorpErrorLight = Color(0xFFDC2626)
val CorpOnErrorLight = Color(0xFFFFFFFF)

val CorpPrimaryDark = Color(0xFF60A5FA)
val CorpOnPrimaryDark = Color(0xFF1E3A8A)
val CorpPrimaryContainerDark = Color(0xFF1E3A8A)
val CorpOnPrimaryContainerDark = Color(0xFFDBEAFE)
val CorpSecondaryDark = Color(0xFF93C5FD)
val CorpOnSecondaryDark = Color(0xFF0F4C81)
val CorpSecondaryContainerDark = Color(0xFF0F4C81)
val CorpOnSecondaryContainerDark = Color(0xFFE0F2FE)
val CorpTertiaryDark = Color(0xFFFBBF24)
val CorpOnTertiaryDark = Color(0xFF78350F)
val CorpBackgroundDark = Color(0xFF111827)
val CorpOnBackgroundDark = Color(0xFFF9FAFB)
val CorpSurfaceDark = Color(0xFF1F2937)
val CorpOnSurfaceDark = Color(0xFFF9FAFB)
val CorpSurfaceVariantDark = Color(0xFF374151)
val CorpOnSurfaceVariantDark = Color(0xFFD1D5DB)
val CorpOutlineDark = Color(0xFF6B7280)
val CorpErrorDark = Color(0xFFF87171)
val CorpOnErrorDark = Color(0xFF7F1D1D)
